# Generated by Django 4.1.3 on 2022-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='default league name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='match name', max_length=30)),
                ('match_date', models.DateTimeField(verbose_name='1970-01-01 00:00:00')),
                ('score_local', models.IntegerField(default=0)),
                ('score_visitor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=30)),
                ('last_name', models.CharField(default='last name', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(verbose_name='1970-01-01 00:00:00')),
            ],
        ),
    ]
