# Generated by Django 4.1.3 on 2022-12-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bzh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='reg_date',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
    ]
