# Generated by Django 4.1.3 on 2022-12-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_bzh', '0002_alter_match_match_date_alter_participant_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='league_bzh.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='league_bzh.participant'),
        ),
    ]
