# Generated by Django 4.1.3 on 2022-12-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_bzh', '0003_match_local_match_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matchleague', to='league_bzh.league'),
        ),
    ]
